from pydantic import BaseModel, Field


# =========================================================
# COORDINATE
# =========================================================

class Coordinate(BaseModel):
    latitude: float
    longitude: float


# =========================================================
# PFZ
# =========================================================

class PFZ(BaseModel):
    id: str
    latitude: float
    longitude: float
    depth_m: float | None = None


# =========================================================
# ROUTE DESTINATION
# =========================================================

class RouteDestination(BaseModel):
    pfz_id: str
    latitude: float
    longitude: float


# =========================================================
# RESTRICTED ZONE
# =========================================================

class RestrictedZone(BaseModel):
    id: str
    name: str
    coordinates: list[list[float]]


# =========================================================
# ROUTE CONSTRAINTS
# =========================================================

class RouteConstraints(BaseModel):
    avoid_restricted_zones: bool = True

    restricted_zones: list[RestrictedZone] = Field(
        default_factory=list
    )


# =========================================================
# ROUTE REQUEST
# =========================================================

class RouteRequest(BaseModel):
    start: Coordinate
    destination: RouteDestination

    time: str | None = None

    constraints: RouteConstraints = Field(
        default_factory=RouteConstraints
    )


# =========================================================
# WAYPOINT
# =========================================================

class Waypoint(Coordinate):
    pass


# =========================================================
# SINGLE ROUTE RESULT
# =========================================================

class RouteResult(BaseModel):
    """
    Represents one candidate route.
    """

    route_id: str | None = None

    pfz_id: str

    start: Coordinate

    destination: Coordinate

    waypoints: list[Waypoint]

    distance_km: float

    geojson: dict


# =========================================================
# MULTIPLE CANDIDATE ROUTES
# =========================================================

class CandidateRoutes(BaseModel):
    """
    Represents multiple routes generated by
    the Route Engine.

    The Risk Engine will evaluate these routes
    and select ONE final route.
    """

    pfz_id: str

    routes: list[RouteResult]